### ISSUE TITLE
无法安装到zhenxun bot

### ISSUE THREAD

**Issue by windyan233** [yajiwa/zhenxun_plugin_petpet#1]
是创建一个新的plugin文件夹放进去，然后pip3 install -r requirements.txt就行了嘛？为什么我这样做之后python bot.py就会报错啊？球球大佬指点~

**Comment by windyan233** [comment]
![image](https://user-images.githubusercontent.com/65809448/171579352-4728e5d6-11fc-49aa-8dc7-de5cb4abe1da.png)

**Comment by windyan233** [comment]
我也已经把nonebot_plugin_imageutils放入plugin文件夹里了，而且还显示已经import了这个模块：
![image](https://user-images.githubusercontent.com/65809448/171579889-3a3e2d9d-71ae-40e1-b54c-a265b2743871.png)

**Comment by windyan233** [comment]
大佬没事了，上个问题我解决了。
![image](https://user-images.githubusercontent.com/65809448/171583519-dc975db5-9486-46c7-863b-9b1859d4f77f.png)
但是现在新的问题就是：已经import了，但是却无法触发？按照下图的信息，感觉是没有成功match
![image](https://user-images.githubusercontent.com/65809448/171583666-f986096f-913a-42e6-ad75-1f8b13dbeb69.png)

**Comment by Fhm-newbie** [comment]
请问您解决了吗？我也有这个问题，一直显示failed to import。。。

**Comment by PercyDan54** [comment]
我的解决方法：把__init__.py中require那行删掉，然后自己在插件里塞imageutils
至于无法触发：__init__.py 65行左右那个priority改成5或者更小

**Comment by Judp28** [comment]
> 我也已经把nonebot_plugin_imageutils放入plugin文件夹里了，而且还显示已经import了这个模块： ![image](https://user-images.githubusercontent.com/65809448/171579889-3a3e2d9d-71ae-40e1-b54c-a265b2743871.png)

为什么我把插件放进去也还会显示 没有nonebot_plugin_imageutils 请问你是怎么解决的呢?

**Comment by Fhm-newbie** [comment]
没解决，我直接换框架用hoshino了发自我的手机-------- 原始邮件 --------发件人： Judp28 ***@***.***>日期： 2022年7月27日周三 下午1:49收件人： yajiwa/zhenxun_plugin_petpet ***@***.***>抄送： Fhm-newbie ***@***.***>, Comment ***@***.***>主    题： Re: [yajiwa/zhenxun_plugin_petpet] 无法安装到zhenxun bot (Issue #1)



我也已经把nonebot_plugin_imageutils放入plugin文件夹里了，而且还显示已经import了这个模块： 



为什么我把插件放进去也还会显示 没有nonebot_plugin_imageutils 请问你是怎么解决的呢?

**Comment by Judp28** [comment]
> 没解决，我直接换框架用hoshino了发自我的手机-------- 原始邮件 --------发件人： Judp28 ***@***.***>日期： 2022年7月27日周三 下午1:49收件人： yajiwa/zhenxun_plugin_petpet ***@***.***>抄送： Fhm-newbie ***@***.***>, Comment ***@***.***>主 题： Re: [yajiwa/zhenxun_plugin_petpet] 无法安装到zhenxun bot (Issue #1) 我也已经把nonebot_plugin_imageutils放入plugin文件夹里了，而且还显示已经import了这个模块： 为什么我把插件放进去也还会显示 没有nonebot_plugin_imageutils 请问你是怎么解决的呢? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

换框架就行了嘛?

**Comment by Fhm-newbie** [comment]
这句话的意思是，我放弃了继续使用zhenxunbot，转而使用hoshinobot。hoshino的插件库里也有相似的插件，如果你愿意自己动手写也可以直接用nonebot，nonebot的插件更多，而且zhenxunbot和hoshinobot的很多插件都是由nonebot的插件魔改而来，甚至zhenxun和hoshino本身就是基于nonebot开发的框架发自我的手机-------- 原始邮件 --------发件人： Judp28 ***@***.***>日期： 2022年7月27日周三 下午2:47收件人： yajiwa/zhenxun_plugin_petpet ***@***.***>抄送： Fhm-newbie ***@***.***>, Comment ***@***.***>主    题： Re: [yajiwa/zhenxun_plugin_petpet] 无法安装到zhenxun bot (Issue #1)



没解决，我直接换框架用hoshino了发自我的手机-------- 原始邮件 --------发件人： Judp28 @.>日期： 2022年7月27日周三 下午1:49收件人： yajiwa/zhenxun_plugin_petpet @.>抄送： Fhm-newbie @.>, Comment @.>主 题： Re: [yajiwa/zhenxun_plugin_petpet] 无法安装到zhenxun bot (Issue #1) 我也已经把nonebot_plugin_imageutils放入plugin文件夹里了，而且还显示已经import了这个模块： 为什么我把插件放进去也还会显示 没有nonebot_plugin_imageutils 请问你是怎么解决的呢? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***>



换框架就行了嘛?

**Comment by Judp28** [comment]
> 这句话的意思是，我放弃了继续使用zhenxunbot，转而使用hoshinobot。hoshino的插件库里也有相似的插件，如果你愿意自己动手写也可以直接用nonebot，nonebot的插件更多，而且zhenxunbot和hoshinobot的很多插件都是由nonebot的插件魔改而来，甚至zhenxun和hoshino本身就是基于nonebot开发的框架发自我的手机-------- 原始邮件 --------发件人： Judp28 ***@***.***>日期： 2022年7月27日周三 下午2:47收件人： yajiwa/zhenxun_plugin_petpet ***@***.***>抄送： Fhm-newbie ***@***.***>, Comment ***@***.***>主 题： Re: [yajiwa/zhenxun_plugin_petpet] 无法安装到zhenxun bot (Issue #1) 没解决，我直接换框架用hoshino了发自我的手机-------- 原始邮件 --------发件人： Judp28 @.>日期： 2022年7月27日周三 下午1:49收件人： yajiwa/zhenxun_plugin_petpet @.>抄送： Fhm-newbie @.>, Comment @.>主 题： Re: [yajiwa/zhenxun_plugin_petpet] 无法安装到zhenxun bot (Issue #1) 我也已经把nonebot_plugin_imageutils放入plugin文件夹里了，而且还显示已经import了这个模块： 为什么我把插件放进去也还会显示 没有nonebot_plugin_imageutils 请问你是怎么解决的呢? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.***> 换框架就行了嘛? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

收到

**Comment by Fhm-newbie** [comment]
没解决，我直接换框架用hoshino了发自我的手机-------- 原始邮件 --------发件人： Judp28 ***@***.***>日期： 2022年7月27日周三 下午1:49收件人： yajiwa/zhenxun_plugin_petpet ***@***.***>抄送： Fhm-newbie ***@***.***>, Comment ***@***.***>主    题： Re: [yajiwa/zhenxun_plugin_petpet] 无法安装到zhenxun bot (Issue #1)



我也已经把nonebot_plugin_imageutils放入plugin文件夹里了，而且还显示已经import了这个模块： 



为什么我把插件放进去也还会显示 没有nonebot_plugin_imageutils 请问你是怎么解决的呢?

**Comment by niucattle** [comment]
![image](https://user-images.githubusercontent.com/118875129/218974137-cee4c401-231f-474c-849d-a23c7f07d3b9.png)
我是这样解决的  相当于指定了一下路径

**Comment by niucattle** [comment]
![EG9)5P%M1F HL9Y 5Q1NU2F](https://user-images.githubusercontent.com/118875129/218975490-66aca3bb-d40e-47cf-9fe9-a2d489e742c3.png)

**Comment by niucattle** [comment]
资源需要自己去https://github.com/noneplugin/nonebot-plugin-petpet 下载
