### ISSUE TITLE
v0.3版本汉字生成异常

### ISSUE THREAD

**Issue by MrMarionette14** [yajiwa/zhenxun_plugin_petpet#2]
操作系统Ubuntu20.04

Python版本3.8.10

真寻版本v0.1.5.9

插件版本v0.3

更新前使用的是2022/5/26下载的版本，能够正常使用。

更新后无法生成汉字，应当出现汉字的地方全部都是空白。

比如“头像表情包”帮助

![image-20220607175136448](https://user-images.githubusercontent.com/32874852/172353432-465c429c-def0-4a9e-9d1b-f632bf234998.png)

或者是“小天使”

![image-20220607175209350](https://user-images.githubusercontent.com/32874852/172353333-08950d30-452e-42d6-86d4-5b11a612570c.png)

插件加载时没有报错，调用时也没有报错。

<img width="1380" alt="Screen Shot 2022-06-07 at 17 53 23" src="https://user-images.githubusercontent.com/32874852/172353536-5108c911-6026-4ef0-9da2-6c01e331d818.png">

**Comment by yajiwa** [comment]
服务器安装中文字体

**Comment by MrMarionette14** [comment]
但是系统已经自带中文字体了，之前的版本也可以正常使用。
<img width="1108" alt="Screen Shot 2022-06-08 at 09 43 13" src="https://user-images.githubusercontent.com/32874852/172513440-aaf5deca-5fca-4b51-9898-2a57ccb41f3a.png">

**Comment by MrMarionette14** [comment]
解决了，根据nonebot_plugin_imageutils下面的指引安装了fonts-noto就好了
