### ISSUE TITLE
关于插件加载报错的问题

### ISSUE THREAD

**Issue by 15220526** [yajiwa/zhenxun_plugin_petpet#3]
这是为什么会出现这种情况的呢
![image](https://user-images.githubusercontent.com/106159640/173134910-a8f69331-499a-40b2-bdd3-67c812440114.png)

**Comment by 15220526** [comment]
还有最后一行
![image](https://user-images.githubusercontent.com/106159640/173135058-ccf6b728-8810-41e3-a4e1-4442990448e5.png)

**Comment by PercyDan54** [comment]
https://github.com/yajiwa/zhenxun_plugin_petpet/issues/1#issuecomment-1152880912
