### ISSUE TITLE
插件启动失败....

### ISSUE THREAD

**Issue by TDuckQWQ** [yajiwa/zhenxun_plugin_petpet#4]
![image](https://user-images.githubusercontent.com/62102282/178667436-1c97355a-7206-45f2-b5c3-053f26a9a8e1.png)

**Comment by 1103859909** [comment]
大哥 你解决了吗

**Comment by TDuckQWQ** [comment]
> 大哥 你解决了吗

下载插件的时候记得进虚拟环境
